### ISSUE TITLE
2.2.9 Not progressing drops

### ISSUE THREAD

**Issue by nexus667** [RakambdaOrg/ChannelPointsMiner#620]
### Description

I did a git pull at the beginning of the week and it did not get any claims for any of the streams it was setup to follow.  On 10/20/2023 I did a git checkout 56473f0 (2.2.8) and rebuild and now it is working again.

### Version / commit

2.2.9

**Comment by Rakambda** [comment]
When you say "claims", is it drops claim?

**Comment by nexus667** [comment]
It is like the stream is not being watched as if you look at your twitch
account there is no progress going on for the drop claim.

**Comment by Rakambda** [comment]
You can try this version and see if it fixes the issue : https://www.dropbox.com/t/IypFESct3ix9odZ3
If you prefer to build it from sources, you can checkout the `hotfix/gh-620` branch.

**Comment by Rakambda** [comment]
The only thing that changed between 2.2.8 & 2.2.9 is how drop live are detected. Before we were looking for a "DropsEnabled" tag, but it seems like it isn't always present on all stream. So i removed that check.
It may be possible that you have another streamer that is falsly being mined because CPM things there's drops to get.

**Comment by nexus667** [comment]
Unknown, I only put specific streamers in as it was a campaign run.  I
noticed that i missed drops all this week as i logged into twitch via the
web and said my last claimed drop was 5 days ago which would coincided when
i updated and put the week worth of streamers in.

**Comment by nexus667** [comment]
I downloaded the dropbox file and I'm seeing progress in the drops now.  If I was trying to use git checkout what other steps do I need to do before running the jar file.

 git checkout -b hotfix/gh-620
Switched to a new branch 'hotfix/gh-620'

**Comment by Rakambda** [comment]
```bash
$ git checkout -b hotfix/https://github.com/RakambdaOrg/ChannelPointsMiner/issues/620
Switched to a new branch 'hotfix/https://github.com/RakambdaOrg/ChannelPointsMiner/issues/620'
$ ./gradlew build -x test
...
$ java -jar miner/build/libs/miner-shaded.jar --settings config.json
```

**Comment by nexus667** [comment]
The download jar file from dropbox worked for the streamers I had setup for Saturday & Sunday.
